export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_MOVIES_BY_SEARCH_TEXT_REQUEST = "FETCH_MOVIES_BY_SEARCH_TEXT_REQUEST";
export const FETCH_MOVIES_BY_SEARCH_TEXT_SUCCESS = "FETCH_MOVIES_BY_SEARCH_TEXT_SUCCESS";
export const FETCH_MOVIES_BY_SEARCH_TEXT_FAILURE = "FETCH_MOVIES_BY_SEARCH_TEXT_FAILURE";

export const FETCH_SINGLE_MOVIE_REQUEST = "FETCH_SINGLE_MOVIE_REQUEST";
export const FETCH_SINGLE_MOVIE_SUCCESS = "FETCH_SINGLE_MOVIE_SUCCESS";
export const FETCH_SINGLE_MOVIE_FAILURE = "FETCH_SINGLE_MOVIE_FAILURE";

export const UPDATE_THEME = "UPDATE_THEME";

export const UPDATE_SEARCH_TEXT = "UPDATE_SEARCH_TEXT";

export const RESET_STATE = "RESET_STATE";